#! /bin/bash

do_commit () {
  git config user.name "Brian Skinn"
  git config user.email "brian.skinn@gmail.com"

  git add . && git commit -m "Commit test log - $( date -uIs )"
  
  if [[ $? -eq 0 ]]
  then
    git push
  fi
}

if [[ $TRIGGER = "schedule" ]]
then
  python -m time_check
  if [[ $? -gt 0 ]]
  then
    echo "Within commit time window, committing log"
    do_commit
    exit 0
  else
    echo "Outside commit time window, no commit"
    exit 0
  fi
fi

if [[ $TRIGGER = "workflow_dispatch" && $COMMIT_OPTION = "Y" ]]
then
  do_commit
  exit 0
fi

echo "No commit, wrong conditions"
