#! /bin/bash

do_commit () {
  git config user.name "Brian Skinn"
  git config user.email "brian.skinn@gmail.com"

  git add . && git commit -m "Commit test log - $( date -uIs )"
  
  if [[ $? -eq 0 ]]
  then
    git push
  fi
}

if [[ $TRIGGER = "schedule" ]]
then
  do_commit
  exit 0
fi

if [[ $TRIGGER = "workflow_dispatch" && $COMMIT_OPTION = "Y" ]]
then
  do_commit
  exit 0
fi

echo "No commit, wrong conditions"
