name: gist-cron

on: 
  push:
    branches:
      - test-*
  schedule:
    - cron: '14 2 */3 * *'
  workflow_dispatch:


jobs:
  link_check:
    name: Check intersphinx gist links
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Update pip
      run: python -m pip install -U pip

    - name: Install & report dependencies
      run: |
        python -m pip install -r requirements.txt
        python --version
        pip list

    - name: Clear log
      run: |
        echo "" > gist-check.log

    - name: Run tests
      run: |
        pytest -v

    - name: Report log
      run: |
        cat gist-check.log
