name: gist-cron

on: 
  push:
    branches:
      - test-*
  schedule:
    - cron: '15 1,13 * * *'
  workflow_dispatch:
    inputs:
      do_commit:
        description: 'Commit log file back to branch (y/n)?'
        required: true
        default: 'n'


jobs:
  link_check:
    name: Check intersphinx gist links
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Update pip
      run: python -m pip install -U pip

    - name: Install & report dependencies
      run: |
        python -m pip install -r requirements.txt
        python --version
        pip list

    - name: Clear log
      run: |
        echo "" > gist-check.log

    - name: Run tests
      run: |
        pytest -v

    - name: Report log
      run: |
        cat gist-check.log

    - name: Commit log (depending)
      env:
        TRIGGER: ${{ github.event_name }}
        COMMIT_OPTION: ${{ github.event.inputs.do_commit }}
      run: |
        COMMIT_OPTION=$( echo ${COMMIT_OPTION^} | cut -c1-1 )
        echo TRIGGER is "'"$TRIGGER"'"
        echo COMMIT_OPTION is "'"$COMMIT_OPTION"'"
        ./do_commit
